### ISSUE TITLE
大佬  有办法屏蔽队友使用草船借箭吗？有时候会翻车

### ISSUE THREAD

**Issue by jiangmw** [luanheart/sgs_script#1]

**Comment by luanheart** [comment]
这个没办法，超纲了。手动刷也是一样的，出现的概率很小的，可以忽略

**Comment by christensennn** [comment]
应该说目前而言导致翻车的东西很多（比如锦囊和武器的使用），草船这个还是次要的。不过改进什么的慢慢来吧，能快速日常签到就不错了。总之谢谢大佬

**Comment by luanheart** [comment]
你说的 逐鹿天下100关-关张 吗，这个没考虑太多，只会装青釭剑、拆仁王、塞装备等，然后出杀，建议用袁绍的脚本刷，虽然慢一点但是很稳

**Comment by christensennn** [comment]
我指120魏平香 像贯石斧和丈八还是该装的 然后优先使用顺手过拆这些破坏手牌的锦囊也不错

**Comment by luanheart** [comment]
120关直接用关张呀，触发草船借箭，不可能翻车的。因为这些逻辑复杂就没写了。

**Comment by jiangmw** [comment]
请问怎么获得英雄generalID啊？
new CompeteWorldBattleGeneralInfo;
        o1.generalID = 28;
        o1.location = 1;
        o1.generalTyp = 2;

location是固定123位置吧？generalTyp是不是也是固定传2？
我尝试这么写，但是进入游戏根本不会打印：
`
CompeteWorldManager.prototype.ReqCompeteWorldBattle = function (t, e) {
	console.log(e);
	this.protoProxy.SendProto(ProtoBufId.CMSG_CREQCOMPETEWORLDBATTLE, {
		towerID: t,
		battleGeneral: e
	})
}
`
求大佬教一下用什么方式获取英雄id?谢谢了

**Comment by luanheart** [comment]
首先在控制台输入以下代码：
```
console.log = function (...data) {
    // 过滤一些日志
    var filterIds = [
        1843119829,//cmsg.CNotifyChatMessage 聊天消息
        1259047180,//cmsg.CNotifyGuildGameStatus
        2351489107
    ]
    if (data.length > 2) {
        for (var id in filterIds) {
            if (data[1].indexOf(id) > -1) {
                return
            }
        }
    }
    console.info(...data)
    // console.trace()
}

ProtoProxy.GetInstance().SendProto = function (t, e) {
    var n = new ProtoVO;
    n.protoID = t,
    n.protoData = e,
    console.info("%o", "--------[SendProto][  Sent  ] ID:" + n.protoID + " name:" + n.ProtoName + " detail:", n.protoData)
    // console.trace()
    ProtoProxy.GetInstance().SendProtocol(n)
}
```
会打印log以及打印接口入参，然后你选择武将开始后就会打印相关信息了，里面就有generalID

**Comment by jiangmw** [comment]
大佬np啊，果然看到了
